# Generated by Django 2.2.9 on 2020-01-21 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('background', models.CharField(max_length=100)),
                ('likes', models.TextField(max_length=350)),
                ('age', models.IntegerField()),
            ],
        ),
    ]
